/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cliente;

import java.awt.Color;
import mensagem.mensagem;
import java.io.ObjectInputStream;
import java.net.Socket;

/**
 *
 * @author a
 */
public class cliente extends javax.swing.JFrame {

    /**
     * Creates new form cliente
     */
    public cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taCores = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        tfip = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfPorta = new javax.swing.JTextField();
        bt2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Gerar Cor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 316, -1));

        taCores.setColumns(20);
        taCores.setRows(5);
        jScrollPane1.setViewportView(taCores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        jLabel1.setText("IP:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 37, -1));

        tfip.setText("127.0.0.1");
        getContentPane().add(tfip, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 75, -1));

        jLabel2.setText("Porta:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 37, -1));

        tfPorta.setText("12345");
        getContentPane().add(tfPorta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 75, -1));

        bt2.setFocusPainted(false);
        getContentPane().add(bt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 320, 390, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
        System.out.println("CLIENTE");
        try {
            Socket cliente = new Socket(tfip.getText(),Integer.parseInt(tfPorta.getText()));
            
            ObjectInputStream entrada = new ObjectInputStream(cliente.getInputStream());
           // mensagem.msgLog(taCores, entrada.readObject().toString());
           
            
             
            
            
            
              //String mensagemRecebida = (String) entrada.readObject(); // Lê a mensagem
    Color corRecebida = (Color) entrada.readObject(); // Lê a cor
    entrada.close();
    
    //mensagem.msgLog(taCores, mensagemRecebida);
    trocarcorbt(corRecebida);
    mensagem.msgLog(taCores, "Ligação Terminada");
    cliente.close();
        } catch (Exception e) {
            mensagem.msgLog(taCores,"Erro: "+ e.getMessage());
        }       
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public void trocarcorbt(Color color){
        bt2.setBackground(color);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taCores;
    private javax.swing.JTextField tfPorta;
    private javax.swing.JTextField tfip;
    // End of variables declaration//GEN-END:variables
}
