/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mcavaliacao2;

import java.util.Scanner;
import javax.swing.JTextField;
import javax.swing.JOptionPane;

/**
 *
 * @author a
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MCTextField1 = new javax.swing.JTextField();
        MCLoginTexto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        MCBotaoEnviar = new javax.swing.JButton();
        MCTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(456, 429));

        MCTextField1.setText("Insira aqui seu login...");
        MCTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MCTextField1FocusGained(evt);
            }
        });
        MCTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MCTextField1MouseClicked(evt);
            }
        });
        MCTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCTextField1ActionPerformed(evt);
            }
        });

        MCLoginTexto.setText("Login");

        jLabel1.setText("Senha");

        MCBotaoEnviar.setText("Submeter");
        MCBotaoEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCBotaoEnviarActionPerformed(evt);
            }
        });

        MCTextField2.setText("Insira aqui sua senha...");
        MCTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MCTextField2FocusGained(evt);
            }
        });
        MCTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MCTextField2MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mcavaliacao2/TESTANDO.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MCLoginTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MCTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MCTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(MCBotaoEnviar)))
                .addContainerGap(432, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MCLoginTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MCTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MCTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MCBotaoEnviar)
                .addGap(51, 51, 51))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MCTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MCTextField1ActionPerformed

    private void MCTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MCTextField1MouseClicked
 if (((JTextField)evt.getSource()).getText().equals("Insira aqui seu login...")); 
        ((JTextField)evt.getSource()).setText("");            // TODO add your handling code here:
    }//GEN-LAST:event_MCTextField1MouseClicked

    private void MCBotaoEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCBotaoEnviarActionPerformed
      this.setVisible(false);
      if (MCTextField1.getText().equals("admin") && MCTextField2.getText().equals("admin")){
        oferta o = new oferta("login");
        o.setVisible(true);
      }
      else
      {
          JOptionPane.showMessageDialog(rootPane, "Campos Inseridos incorretamente!");
      System.exit(0);
      }
    }//GEN-LAST:event_MCBotaoEnviarActionPerformed

    private void MCTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MCTextField2MouseClicked
       if (((JTextField)evt.getSource()).getText().equals("Insira aqui sua senha...")); 
        ((JTextField)evt.getSource()).setText("");       // TODO add your handling code here:
    }//GEN-LAST:event_MCTextField2MouseClicked

    private void MCTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MCTextField2FocusGained
        MCTextField2.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_MCTextField2FocusGained

    private void MCTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MCTextField1FocusGained
        MCTextField1.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_MCTextField1FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MCBotaoEnviar;
    private javax.swing.JLabel MCLoginTexto;
    private javax.swing.JTextField MCTextField1;
    private javax.swing.JTextField MCTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
