/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;
import java.awt.Color;
import static java.lang.Thread.sleep;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author a
 */
public class Jogo extends javax.swing.JFrame {

    /**
     * Creates new form Jogo
     */
    public Jogo(String nome) {
        initComponents();
        lbNomePlayer.setText("Olá "+nome);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNomePlayer = new javax.swing.JLabel();
        btnVerde = new javax.swing.JButton();
        btnVermelho = new javax.swing.JButton();
        btnAmarelo = new javax.swing.JButton();
        btnAzul = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        score = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lbNomePlayer.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbNomePlayer.setText("                 Olá");
        lbNomePlayer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnVerde.setBackground(new java.awt.Color(51, 153, 0));
        btnVerde.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerdeActionPerformed(evt);
            }
        });

        btnVermelho.setBackground(new java.awt.Color(255, 0, 0));
        btnVermelho.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnVermelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVermelhoActionPerformed(evt);
            }
        });

        btnAmarelo.setBackground(new java.awt.Color(255, 255, 0));
        btnAmarelo.setForeground(new java.awt.Color(255, 255, 0));
        btnAmarelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAmarelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmareloActionPerformed(evt);
            }
        });

        btnAzul.setBackground(new java.awt.Color(0, 102, 204));
        btnAzul.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAzulActionPerformed(evt);
            }
        });

        jButton5.setText("Iniciar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        score.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        score.setText("Score: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(score, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(215, 215, 215))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbNomePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAmarelo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVermelho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAzul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNomePlayer)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVermelho, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAmarelo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(score))
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVermelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVermelhoActionPerformed
        verifica(1);        // TODO add your handling code here:
    }//GEN-LAST:event_btnVermelhoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jogada = 0;
        sequencia.clear();
        sequencia.add(gerarNumero());
        varreepisca();
        jButton5.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerdeActionPerformed
    verifica(0);

// TODO add your handling code here:
    }//GEN-LAST:event_btnVerdeActionPerformed

    private void btnAmareloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmareloActionPerformed
    verifica(2);        // TODO add your handling code here:
    }//GEN-LAST:event_btnAmareloActionPerformed

    private void btnAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAzulActionPerformed
    verifica(3);        // TODO add your handling code here:
    }//GEN-LAST:event_btnAzulActionPerformed

    private int gerarNumero()
    {
       Random r = new Random();
       return r.nextInt(4);
    }
    
    private void foco(int posicao)
    {
        //System.out.println(posicao);
        
        switch(posicao)
        {
            case 0: btnVerde.requestFocus();
                    btnVerde.setBackground(new java.awt.Color(0, 230, 0));
                    break;
            case 1: btnVermelho.requestFocus();
                    btnVermelho.setBackground(new java.awt.Color(255, 17, 33));
                    break;
            case 2: btnAmarelo.requestFocus();
                    btnAmarelo.setBackground(new java.awt.Color(255, 255, 99));
                    break;
            case 3: btnAzul.requestFocus();
                    btnAzul.setBackground(new java.awt.Color(0, 147, 220));
                    break;       
        }
    }
    
    private void btnDefault()
    {
        btnVermelho.setBackground(new java.awt.Color(255, 0, 0));
        btnAzul.setBackground(new java.awt.Color(0, 102, 204));
        btnAmarelo.setBackground(new java.awt.Color(255, 255, 0));
        btnVerde.setBackground(new java.awt.Color(51, 153, 0));
    }
    
    private void fazerReset()
    {
        jButton5.setVisible(true);
    }
    
    private void verifica(int cor)
    {
        if(cor != sequencia.get(jogada)){
            fazerReset();
            //System.out.println("Perdeu");
        }
            else{
            jogada++;
                if (jogada == sequencia.size())
            {
            jogada = 0;
            sequencia.add(gerarNumero());
            varreepisca();
            //System.out.println("fim turno");
            score.setText("Score: "+ (sequencia.size()-1));
            
            }
        }
    }
    
    private void varreepisca()
    {   
        Thread t1 = new Thread() {
            public void run(){
                for(int i=0;i < sequencia.size() ; i++){
                       System.out.println(sequencia.get(0));
                       foco(sequencia.get(i));
                
                try {
                    sleep(1000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Jogo.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                    try {
                        btnDefault();
                        sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Jogo.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }       
            }
        };
        
        t1.start();
    }
    
    private void piscartudo(){
        btnVermelho.setBackground(new java.awt.Color(255, 255, 255));
        btnAzul.setBackground(new java.awt.Color(255, 255, 255));
        btnAmarelo.setBackground(new java.awt.Color(255, 255, 255));
        btnVerde.setBackground(new java.awt.Color(255, 255, 255));
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jogo("").setVisible(true);
            }
        });
    }
    
    private ArrayList<Integer> sequencia = new ArrayList();
    private int jogada;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAmarelo;
    private javax.swing.JButton btnAzul;
    private javax.swing.JButton btnVerde;
    private javax.swing.JButton btnVermelho;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel lbNomePlayer;
    private javax.swing.JLabel score;
    // End of variables declaration//GEN-END:variables
}
